-- ============================================================
--  Exceptions de permissions par compte individuel
--
--  Le systeme existant (table `permissions`) ne connait que role_id+module :
--  decocher un droit s'applique a TOUS les comptes du role. Demande : pouvoir
--  retirer (ou accorder) un droit a UN compte precis sans toucher aux autres
--  comptes du meme role (ex: 4 comptes "Superviseur Operation", un seul perd
--  can_delete sur bobines).
--
--  3 etats par droit, colonnes NULLABLES (pas de DEFAULT 0/1) :
--    NULL -> pas de surcharge, le droit du role s'applique tel quel
--    0    -> refuse explicitement, meme si le role l'autorise
--    1    -> autorise explicitement, meme si le role le refuse
--  Une ligne peut donc exister pour un module avec seulement certains droits
--  surcharges (ex: can_delete=0, les 4 autres colonnes NULL) : UNIQUE
--  (user_id, module), pas de role_id — l'exception suit le compte, pas son
--  role courant (un changement de role doit faire revalider consciemment
--  les exceptions existantes, pas les reappliquer automatiquement).
--
--  smallint et non boolean : meme convention que `permissions`
--  (can_create/can_read/... y sont deja smallint).
--
--  Consultee dans can() (includes/session.php) en tout dernier recours,
--  juste avant le fallback role->permissions, sans jamais court-circuiter
--  les cas speciaux existants (inventaire_sessions, N+1 gestionnaire de
--  stock, support_it, gestionnaire_operation) qui retournent deja leur
--  propre resultat avant d'atteindre ce point.
--
--  Idempotente : CREATE TABLE/INDEX IF NOT EXISTS.
--  2026-10
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_permissions (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    module      varchar(60) NOT NULL,
    can_create  smallint DEFAULT NULL,
    can_read    smallint DEFAULT NULL,
    can_update  smallint DEFAULT NULL,
    can_delete  smallint DEFAULT NULL,
    can_export  smallint DEFAULT NULL,
    created_by  integer REFERENCES public.users(id),
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_permissions_user_module_uniq UNIQUE (user_id, module)
);

CREATE INDEX IF NOT EXISTS idx_user_permissions_user ON public.user_permissions (user_id);

COMMENT ON TABLE public.user_permissions IS
    'Surcharges de permissions par compte individuel. NULL = herite du role (table permissions), 0 = refuse explicitement, 1 = autorise explicitement. Ne remplace jamais la table permissions, vient en dernier recours par-dessus elle (cf. can() dans includes/session.php).';
